# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.


[[main]]
  name = "TRAIN"  
  pageRef = "TRAIN"
  weight = 10
[[main]]
  parent = "TRAIN"
  name = "Exercise"
  pageRef = "Exercise"
[[main]]
  parent = "TRAIN"
  name = "Focus"
  pageRef = "Focus"
[[main]]
  parent = "TRAIN"
  name = "Gratitude"
  pageRef = "Gratitude"
[[main]]
  parent = "TRAIN"
  name = "Hydrate"
  pageRef = "Hydrate"
[[main]]
  parent = "TRAIN"
  name = "Mediate"
  pageRef = "Meditate"
[[main]]
  parent = "TRAIN"
  name = "Sleep"
  pageRef = "Sleep"
    

[[main]]
  name = "LEARN"  
  pageRef = "LEARN"
  weight = 20
[[main]]
  parent = "LEARN"
  name = "Physics"
  pageRef = "Physics"
[[main]]
  parent = "LEARN"
  name = "Maths"
  pageRef = "Maths"
[[main]]
  parent = "LEARN"
  name = "Mathematica"
  pageRef = "Mathematica"
[[main]]
  parent = "LEARN"
  name = "German"
  pageRef = "German"
[[main]]
  parent = "LEARN"
  name = "Programming"
  pageRef = "Programming"
[[main]]
  parent = "LEARN"
  name = "Thesis"
  pageRef = "Thesis"
[[main]]
  parent = "LEARN"
  name = "CAD"
  pageRef = "CAD"


[[main]]
  name = "REFLECT"  
  pageRef = "REFLECT"
  weight = 30


[[main]]
  name = "ACHIEVE"
  pageRef = "ACHIEVE"
  weight = 40



[[subnavigation]]
  name = "Quote of the day"
  pageRef = "quotes.md"



# [[subnavigation]]
#   name = "An interesting topic"
#   pageRef = "tags/interesting-topic"
#   weight = 10

# [[subnavigation]]
#   name = "My Awesome Category"
#   pre = "github"
#   pageRef = "categories/awesome"
#   weight = 20

# [[main]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20

# [[main]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 10

[[footer]]
  name = "Categories"
  pageRef = "categories"
  weight = 20
